### ISSUE TITLE
When I execute, this error is showing

### ISSUE THREAD

**Issue by vieiraeduardos** [apoorva-dave/LicensePlateDetector#2]
Traceback (most recent call last):
  File "DetectPlate.py", line 26, in <module>
    car_image = imread("./output/frame%d.jpg"%(count-1), as_grey=True)
  File "/usr/local/lib/python2.7/dist-packages/skimage/io/_io.py", line 97, in imread
    img = call_plugin('imread', fname, plugin=plugin, **plugin_args)
  File "/usr/local/lib/python2.7/dist-packages/skimage/io/manage_plugins.py", line 209, in call_plugin
    return func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/skimage/io/_plugins/pil_plugin.py", line 23, in imread
    im = Image.open(fname)
  File "/usr/lib/python2.7/dist-packages/PIL/Image.py", line 2258, in open
    fp = builtins.open(filename, "rb")
IOError: [Errno 2] No such file or directory: './output/frame-1.jpg'

**Comment by vieiraeduardos** [comment]
I don t change anything

**Comment by vieiraeduardos** [comment]
I fix it.

**Comment by raviteja-1011** [comment]
please provide the correct answer
