### ISSUE TITLE
Windows 10 Fresh Install

### ISSUE THREAD

**Issue by tecnologia-magno** [apoorva-dave/LicensePlateDetector#21]
Run in cmd:
```
ECHO Python python-3.8.5-amd64
ECHO Git-2.28.0-64-bit
CD /D "D:\Wide\jetoil_mod"
"D:\DEV\python385winx64\python.exe" -m pip install --upgrade pip
pip3 install virtualenv
virtualenv --python "D:\DEV\python385winx64\python.exe" venv
.\venv\Scripts\activate
REM GOTO method2
git clone https://github.com/apoorva-dave/LicensePlateDetector
CD LicensePlateDetector
pip3 install -r requirements.txt
python PredictCharacters.py
```

Get error:
```
Traceback (most recent call last):
  File "PredictCharacters.py", line 1, in <module>
    import SegmentCharacters
  File "D:\Wide\jetoil_mod\LicensePlateDetector\SegmentCharacters.py", line 4, in <module>
    from skimage.measure import regionprops
  File "D:\Wide\jetoil_mod\venv\lib\site-packages\skimage\__init__.py", line 125, in <module>
    from .util.dtype import (img_as_float32,
  File "D:\Wide\jetoil_mod\venv\lib\site-packages\skimage\util\__init__.py", line 17, in <module>
    from ._map_array import map_array
  File "D:\Wide\jetoil_mod\venv\lib\site-packages\skimage\util\_map_array.py", line 2, in <module>
    from ._remap import _map_array
ImportError: DLL load failed while importing _remap: The specified module could not be found.
```

Fix by editing SegmentCharacters.py and import matplotlib before skimage
```
import numpy as np
import matplotlib
from skimage.transform import resize
from skimage import measure
from skimage.measure import regionprops
import matplotlib.patches as patches
import matplotlib.pyplot as plt
import DetectPlate
```

**Comment by apoorva-dave** [comment]
Thanks for pointing it out. Can you open a pull request for this?

**Comment by tecnologia-magno** [comment]
Hi, thanks for replying,

I will make the pull request as soon as possible,

See you soon!
