### ISSUE TITLE
List index out of range 

### ISSUE THREAD

**Issue by Avant-Gardiste** [apoorva-dave/LicensePlateDetector#23]
why am i getting list index out of range please ??

**Comment by apoorva-dave** [comment]
Where are you getting this error?

**Comment by Avant-Gardiste** [comment]
Whenever i change the image ! is that normal ?

**Comment by sambhuajay** [comment]
> Where are you getting this error?

In segmentation.py

**Comment by starosek** [comment]
Unfortunately I also get that error when trying to use my own images

Traceback (most recent call last):
  File ".../LicensePlateDetector/PredictCharacters.py", line 1, in <module>
    import SegmentCharacters
  File ".../LicensePlateDetector/SegmentCharacters.py", line 10, in <module>
    license_plate = np.invert(DetectPlate.plate_like_objects[0])
IndexError: list index out of range

**Comment by spinxi** [comment]
I think that's because program doesn't catch plate numbers

**Comment by jarulraj** [comment]
To resolve this indexing error, please consider using this notebook that also supports license plate detection:

https://github.com/georgia-tech-db/eva
https://github.com/georgia-tech-db/license-plate-recognition/blob/main/README.ipynb

![README_15_0](https://user-images.githubusercontent.com/5521975/212554733-09d6ab55-fff8-4b65-b142-906f087ff917.png)
